trigger:
– main

pool:
  vmImage: 'ubuntu-latest'

steps:
– task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

– script: |
    npm install
    CI=true npm run build
  displayName: 'gatsby build'

– task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'public' # public is the name of the default build output folder
    ArtifactName: 'src/public' # this can be called anything you like
    publishLocation: 'Container'