name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [14.x]
    steps:  
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' 
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: _dist
        path: .

    - uses: actions/checkout@v2
    - uses: bacongobbler/azure-blob-storage-upload@main
      with:
        source_dir: _dist
        container_name: www
        connection_string: ${{ secrets.ConnectionString }}
        extra_args: '--pattern *.tar.gz'
        # WARNING: this will overwrite existing blobs in your blob storage
        overwrite: 'true'

