name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [14.x]
    steps:  
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - uses: actions/checkout@v3
    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-

    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: .
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
        name: node-app
        path: |
            dist
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: |
            dist
            !dist/**/*.md
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Deploy the website
      uses: tibor19/static-website-deploy@v2
      with:
        enabled-static-website: 'true'
        folder: dist
        connection-string: ${{ secrets.CONNECTION_STRING }}
